apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: evolve4
spec:
  selector:
    matchLabels:
      app: evolve4
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: evolve4
    spec:     # pod spec
      containers: 
      - name: customer
        ports:
        - containerPort: 1337
          $patch: delete
        - containerPort: containerPortVal  
        env:
        - name: DATABASE_NAME
          value: "evolve4"     
                  
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: evolve4
spec:
  selector:
    app: evolve4


---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-vs
spec:
  hosts: 
    - evolve4.sreyo.in
  http:
    - route:
        - destination:
            host: evolve4-customer-service.default.svc.cluster.local
            port:
              number: portVal